export const cardsData = [
    {
        id: 1,
        title: 'Task 1',
        dateTime: '24/09/2022 16:20 hs.',
        creator: 'Julio Avant',
        description: 'Desc 1',
        type: 'finished',
        priority: 'high',
    },
    {
        id: 2,
        title: 'Task 2',
        dateTime: '24/09/2022 18:45 hs.',
        creator: 'Fernando Cruz',
        description: 'Desc 1',
        type: 'finished',
        priority: 'high',
    },
    {
        id: 3,
        title: 'Task 3',
        dateTime: '25/09/2022 10:20 hs.',
        creator: 'Ahmed Aris',
        description: 'Desc 1',
        type: 'inProcess',
        priority: 'high',
    },
    {
        id: 4,
        title: 'Task 4',
        dateTime: '25/09/2022 15:32 hs.',
        creator: 'Juana Arias',
        description: 'Desc 1',
        type: 'inProcess',
        priority: 'high',
    },
    {
        id: 5,
        title: 'Task 5',
        dateTime: '26/09/2022 14:06 hs.',
        creator: 'Luciano Lollo',
        description: 'Desc 1',
        type: 'new',
        priority: 'high',
    },
    {
        id: 6,
        title: 'Task 6',
        dateTime: '28/09/2022 19:00 hs.',
        creator: 'Julián Álvarez',
        description: 'Desc 1',
        type: 'new',
        priority: 'high',
    },
]